export default [
    {
        "color-scheme": "light",
        "primary": "#570df8",
        "primary-content": "#ffffff",
        "secondary": "#f000b8",
        "accent": "#37cdbe",
        "neutral": "#3d4451",
        "base-100": "#ffffff",
        "info": "#3abff8",
        "success": "#36d399",
        "warning": "#fbbd23",
        "error": "#f87272",
        "theme": "light"
    },
    {
        "color-scheme": "dark",
        "primary": "#793ef9",
        "primary-content": "#ffffff",
        "secondary": "#f000b8",
        "accent": "#37cdbe",
        "neutral": "#2a2e37",
        "base-100": "#121212",
        "info": "#3abff8",
        "success": "#36d399",
        "warning": "#fbbd23",
        "error": "#f87272",
        "theme": "dark"
    },
    {
        "color-scheme": "light",
        "primary": "#65c3c8",
        "primary-content": "#ffffff",
        "secondary": "#ef9fbc",
        "accent": "#eeaf3a",
        "neutral": "#291334",
        "base-100": "#faf7f5",
        "info": "#3abff8",
        "success": "#36d399",
        "warning": "#fbbd23",
        "error": "#f87272",
        "theme": "cupcake"
    },
    {
        "color-scheme": "light",
        "primary": "#e0a82e",
        "primary-content": "#ffffff",
        "secondary": "#f9d72f",
        "accent": "#fde68a",
        "neutral": "#181830",
        "base-100": "#ffffff",
        "info": "#3abff8",
        "success": "#36d399",
        "warning": "#fbbd23",
        "error": "#f87272",
        "theme": "bumblebee"
    },
    {
        "color-scheme": "light",
        "primary": "#66cc8a",
        "primary-content": "#ffffff",
        "secondary": "#377cfb",
        "accent": "#ea5234",
        "neutral": "#333c4d",
        "base-100": "#ffffff",
        "info": "#3abff8",
        "success": "#36d399",
        "warning": "#fbbd23",
        "error": "#f87272",
        "theme": "emerald"
    },
    {
        "color-scheme": "light",
        "primary": "#4b6bfb",
        "primary-content": "#ffffff",
        "secondary": "#7b92b2",
        "accent": "#67cba0",
        "neutral": "#181a2a",
        "base-100": "#ffffff",
        "info": "#3abff8",
        "success": "#36d399",
        "warning": "#fbbd23",
        "error": "#f87272",
        "theme": "corporate"
    },
    {
        "color-scheme": "dark",
        "primary": "#d427fc",
        "primary-content": "#ffffff",
        "secondary": "#ff00f7",
        "accent": "#2de2e6",
        "neutral": "#1a132b",
        "base-100": "#2d1b69",
        "info": "#66ffe6",
        "success": "#7cffc3",
        "warning": "#ffd470",
        "error": "#fc5e5a",
        "theme": "synthwave"
    },
    {
        "color-scheme": "dark",
        "primary": "#ef4565",
        "primary-content": "#ffffff",
        "secondary": "#ffc900",
        "accent": "#b3c9ff",
        "neutral": "#181a2a",
        "base-100": "#1d232a",
        "info": "#3abff8",
        "success": "#36d399",
        "warning": "#fbbd23",
        "error": "#f87272",
        "theme": "retro"
    },
    {
        "color-scheme": "dark",
        "primary": "#ff7597",
        "primary-content": "#2e2e2e",
        "secondary": "#a2d2ff",
        "accent": "#caffbf",
        "neutral": "#1b1f23",
        "base-100": "#101010",
        "info": "#3abff8",
        "success": "#36d399",
        "warning": "#fbbd23",
        "error": "#f87272",
        "theme": "cyberpunk"
    },
    {
        "color-scheme": "light",
        "primary": "#e05a47",
        "primary-content": "#ffffff",
        "secondary": "#f69a9c",
        "accent": "#ffe4d6",
        "neutral": "#9e4f52",
        "base-100": "#fdf5f5",
        "info": "#3abff8",
        "success": "#36d399",
        "warning": "#fbbd23",
        "error": "#f87272",
        "theme": "valentine"
    },
    {
        "color-scheme": "dark",
        "primary": "#f97316",
        "primary-content": "#3d2b1f",
        "secondary": "#facc15",
        "accent": "#2f2f2f",
        "neutral": "#161c22",
        "base-100": "#0d131a",
        "info": "#3abff8",
        "success": "#36d399",
        "warning": "#fbbd23",
        "error": "#f87272",
        "theme": "halloween"
    },
    {
        "color-scheme": "light",
        "primary": "#88b040",
        "primary-content": "#ffffff",
        "secondary": "#c4d82d",
        "accent": "#37cdbe",
        "neutral": "#364425",
        "base-100": "#f8fdf6",
        "info": "#3abff8",
        "success": "#36d399",
        "warning": "#fbbd23",
        "error": "#f87272",
        "theme": "garden"
    },
    {
        "color-scheme": "light",
        "primary": "#5a9258",
        "primary-content": "#ffffff",
        "secondary": "#3b8a4d",
        "accent": "#8cbf88",
        "neutral": "#181d1b",
        "base-100": "#e4ebe4",
        "info": "#3abff8",
        "success": "#36d399",
        "warning": "#fbbd23",
        "error": "#f87272",
        "theme": "forest"
    },
    {
        "color-scheme": "light",
        "primary": "#66cc8a",
        "primary-content": "#ffffff",
        "secondary": "#377cfb",
        "accent": "#ea5234",
        "neutral": "#3c4d4f",
        "base-100": "#d8e0e2",
        "info": "#3abff8",
        "success": "#36d399",
        "warning": "#fbbd23",
        "error": "#f87272",
        "theme": "aqua"
    },
    {
        "color-scheme": "dark",
        "primary": "#4a5568",
        "primary-content": "#e2e8f0",
        "secondary": "#a0aec0",
        "accent": "#718096",
        "neutral": "#2d3748",
        "base-100": "#1a202c",
        "info": "#3abff8",
        "success": "#48bb78",
        "warning": "#ecc94b",
        "error": "#f56565",
        "theme": "nord"
    },
    {
        "color-scheme": "dark",
        "primary": "#0077b6",
        "primary-content": "#023047",
        "secondary": "#ffd60a",
        "accent": "#f77f00",
        "neutral": "#14213d",
        "base-100": "#1b1b1b",
        "info": "#56cfe1",
        "success": "#80ed99",
        "warning": "#ffb703",
        "error": "#d00000",
        "theme": "dim"
    },
    {
        "color-scheme": "dark",
        "primary": "#9d0208",
        "primary-content": "#fdf4e3",
        "secondary": "#e85d04",
        "accent": "#faa307",
        "neutral": "#370617",
        "base-100": "#000000",
        "info": "#219ebc",
        "success": "#52b788",
        "warning": "#ffba08",
        "error": "#f94144",
        "theme": "autumn"
    },
    {
        "color-scheme": "light",
        "primary": "#80b918",
        "primary-content": "#fafafa",
        "secondary": "#d4a373",
        "accent": "#b7b7a4",
        "neutral": "#a98467",
        "base-100": "#fffdf4",
        "info": "#81b29a",
        "success": "#2d6a4f",
        "warning": "#c67d0a",
        "error": "#a11f1f",
        "theme": "sunset"
    },
    {
        "color-scheme": "light",
        "primary": "#f72585",
        "primary-content": "#ffffff",
        "secondary": "#3a0ca3",
        "accent": "#7209b7",
        "neutral": "#1a1a40",
        "base-100": "#f8f9fa",
        "info": "#4361ee",
        "success": "#4cc9f0",
        "warning": "#ffd60a",
        "error": "#dc2f02",
        "theme": "fantasy"
    }
];
