import { Toaster } from "sonner";
import Header from "./_components/Header";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "next-themes";
import { shadesOfPurple } from "@clerk/themes";
import Footer from "./_components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: shadesOfPurple,
        variables: {
          colorPrimary: "#3b82f6",
          colorBackground: "#000",
          colorInputBackground: "#2D3748",
          colorInputText: "#F3F4F6",
        },
        elements: {
          formButtonPrimary: "bg-indigo-800 hover:bg-indigo-900 text-white",
          card: "gradient-background2",
          headerTitle: "text-indigo-800",
          headerSubtitle: "text-purple-700",
        },
      }}
    >
      <html lang="en" suppressHydrationWarning>
        <body className="">
          {/* <ThemeProvider attribute="class" defaultTheme="light"> */}
          <Header />
          <Toaster richColors />
          <main className="min-h-screen">{children}</main>
          <Toaster richColors />

          <Footer />

          {/* </ThemeProvider> */}
        </body>
      </html>
    </ClerkProvider>
  );
}
